@startuml Manage Hotel (GET ONE)

header Sample Hotel Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Hotel (GET ONE)"

participant "Client" as client
participant "<<JavaScript>>\n:Server" as server
participant "<<Router>>\n:Hotels" as routerHotels
participant "<<Controllers>>\n:Hotels" as controllersHotels
participant "<<Model>>\n:Hotel" as modelHotel
database "<<MongoDB>>\n:hotels" as HotelsDatabase

client -> server ++:req.get('/hotel/:id')
server -> routerHotels ++:app.use('/hotel', hotel)
routerHotels -> controllersHotels ++:getHotel()
controllersHotels -> modelHotel ++:findById(req.params.id)
modelHotel -> HotelsDatabase ++: HotelSchema
HotelsDatabase --> modelHotel --: hotel
controllersHotels <-- modelHotel --: hotel
controllersHotels -> client --: response

@enduml
