@startuml Manage Hotels (GET ALL)

header Sample Hotels Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Hotels (GET ALL)"

participant "Client" as client
participant "<<JavaScript>>\n:Server" as server
participant "<<Router>>\n:Hotels" as routerHotels
participant "<<Controllers>>\n:Hotels" as controllersHotels
participant "<<Model>>\n:Hotel" as modelHotel
database "<<MongoDB>>\n:hotels" as HotelsDatabase

client -> server ++:req.get('/hotels')
server -> routerHotels ++:app.use('/hotels', hotels)
routerHotels -> controllersHotels ++:getHotels()
controllersHotels -> modelHotel ++:find(query)
modelHotel -> HotelsDatabase ++: HotelSchema
HotelsDatabase --> modelHotel --: hotels
controllersHotels <-- modelHotel --: hotels
controllersHotels -> client --:response

@enduml
