@startuml Update Booking

header Update Booking Sequence Diagram
footer Page %page% of %lastpage%
title "Update Booking"

participant "Client" as client
participant "<<JavaScript>>\n:Server" as server
participant "<<Router>>\n:Booking" as routerBookings
participant "<<Controllers>>\n:Bookings" as controllersBookings
participant "<<Model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client -> server ++:req.put('/booking/:id')
server -> routerBookings ++:app.use('/booking', booking)
routerBookings -> controllersBookings ++:updateBooking()
controllersBookings -> modelBooking ++:findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true })
modelBooking -> BookingsDatabase ++: Update booking in database
BookingsDatabase --> modelBooking: booking
controllersBookings <-- modelBooking --: response

@enduml
