@startuml
!define RECTANGLE class

RECTANGLE User {
  + Name
  + Telephone Number
  + Email
  + Password
  --
  + Register()
  + Log In()
  + Log Out()
  + Book Hotel()
  + View Bookings()
  + Edit Bookings()
  + Delete Bookings()
}

RECTANGLE Admin {
  --
  + View Bookings()
  + Edit Bookings()
  + Delete Bookings()
}

RECTANGLE System {
  + Provide Hotel List
}

User --|> System
Admin --|> System
@enduml
